#!/usr/bin/env ruby

require_relative 'bootstrap_ar'

action = ARGV[0]
target = ARGV[1]
flag = ARGV[2]

if action == "add"
  Task.create( name: target )
elsif action == "list"
  tasks = Task.all
  tasks.each_with_index do |task, i|
    check = " "
    check = "x" if task.complete?
    puts "#{task.id} [#{check}] #{task.name}"
  end
elsif action == "delete"
  matching_task = Task.where( id: target ).all
  matching_task.each do |task|
    task.destroy
  end
elsif action == "mark"
  target_task = Task.find_by_id(target)
  target_task.complete = true
  target_task.save
elsif action == "unmark"
  target_task = Task.find_by_id(target)
  target_task.complete = false
  target_task.save
end




time_for_beer = <<-eos
   .:.
 _oOoOo  Nothing to do
[_|||||  time for beer
  |||||        -tskr
  ~~~~~
eos